title: Dion Snoeijen
email: hallo@dionsnoeijen.nl
description: "Developer" #
baseurl: "" #
url: "https://dionsnoeijen.nl"
twitter_username: dionsnoeijen
github_username: dionsnoeijen

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
sass:
 style: compressed
